# Module 1.1- Linear Algebra - Problems and Solutions

In [2]:
import numpy as np

### 1) For each of the following cases, express the following elements (matrices or vectors) and check whether the operation can be performed. If so, perform the operation 

#### a)          $ A = \begin{pmatrix} 9 & \sqrt(2) & -3 \end{pmatrix}$ and $B = \begin{pmatrix} 5& 0 & 16 \end{pmatrix}$

$C = A+B$ \
$D = A*B$

In [3]:
A = np.array([[9, np.sqrt(2), -3]])
B = np.array([[5, 0, 16]])

print(A)
print(B)

[[ 9.          1.41421356 -3.        ]]
[[ 5  0 16]]


In [4]:
print(A.shape)
print(B.shape)

(1, 3)
(1, 3)


In [5]:
C = A+B
print(C)

[[14.          1.41421356 13.        ]]


In [10]:
D = A@B
print(D)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 3)

#### b)          $ A = \begin{pmatrix} 9 & \sqrt(2) & -3 \end{pmatrix}$ and $B = \begin{pmatrix} 25 \\ 33 \\ -9 \end{pmatrix}$

$C = A-B$ \
$D = A*B$

In [11]:
A = np.array([[9, np.sqrt(2), -3]])
B = np.array([[25],[33],[-9]])

print(A)
print(B)

[[ 9.          1.41421356 -3.        ]]
[[25]
 [33]
 [-9]]


In [12]:
print(A.shape)
print(B.shape)

(1, 3)
(3, 1)


In [13]:
C = A - B
print(C) #Broadcasting 

[[-16.         -23.58578644 -28.        ]
 [-24.         -31.58578644 -36.        ]
 [ 18.          10.41421356   6.        ]]


In [15]:
D = A*B
print(D)

[[225.          35.35533906 -75.        ]
 [297.          46.66904756 -99.        ]
 [-81.         -12.72792206  27.        ]]


#### c)          $ A = \begin{pmatrix} 9 & 2 \\ -4 & 8 \\ 0 & 1  \end{pmatrix}$ and $B = \begin{pmatrix} 5 & 0 & -1\\ 3 & 3 & 7\end{pmatrix}$

$C = A*B$ \
$D = B*A$

In [19]:
A = np.array([[9, 2], [-4, 8], [0,1]])
B = np.array([[5,0,-1],[3,3,7]])

print(A)

[[ 9  2]
 [-4  8]
 [ 0  1]]


In [20]:
print(B)

[[ 5  0 -1]
 [ 3  3  7]]


In [21]:
print(A.shape)
print(B.shape)

(3, 2)
(2, 3)


In [23]:
C = A@B
print(C)

[[51  6  5]
 [ 4 24 60]
 [ 3  3  7]]


In [24]:
D = B@A
print(D)

[[45  9]
 [15 37]]


#### c)          $ A = \begin{pmatrix} 1 & 2 \\ -2 & 6 \\ 1 & 3  \end{pmatrix}$ and $B = \begin{pmatrix} -1\\ 3 \\ 7\end{pmatrix}$

$C = A^T*B$ \
$D = B*A$

In [38]:
A = np.array([[1,2],[-2,6],[1,3]])
B = np.array([[-1],[3],[7]])

print(A)
print(B)

[[ 1  2]
 [-2  6]
 [ 1  3]]
[[-1]
 [ 3]
 [ 7]]


In [39]:
print(A.shape)
print(B.shape)

(3, 2)
(3, 1)


In [40]:
print(A.T.shape)
print(B.shape)

(2, 3)
(3, 1)


In [41]:
C = A.T@B
print(C)

[[ 0]
 [37]]


In [42]:
print(B.shape)
print(A.shape)

(3, 1)
(3, 2)


In [43]:
D = B@A #No se puede realizar 

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 1)

### 2) For each of the following cases, check if the system have solution(s). Compute the solution in case exist or compute an approximate solution if apply. 

#### a) 
$x_1 +2x_2 -3x_3 = 9$ \
$2x_1 -x_2 +x_3 = 0$ \
$4x_1 -x_2 +x_3 = 4$

$Ax = b$

In [45]:
A = np.array([[1,2,-3],[2,-1,1],[4,-1,1]])
print(A)

[[ 1  2 -3]
 [ 2 -1  1]
 [ 4 -1  1]]


In [46]:
A.shape

(3, 3)

In [47]:
np.linalg.det(A)

-1.9999999999999993

In [48]:
np.linalg.matrix_rank(A)

3

In [49]:
b = np.array([[9],[0],[4]])

$x = A^{-1}b$

In [52]:
x = np.linalg.inv(A)@b
print(x)

[[2.]
 [5.]
 [1.]]


#### b) 
$-x_1 + 3x_2 -2x_3 +4x_4= 0$ \
$2x_1 -6x_2 +x_3 -2x_4 = -3$ \
$x_1 -3x_2 +4x_3 -8x4= 2$

In [53]:
A = np.array([[-1, 3, -2, 4], [2, -6, 1, -2], [1, -3, 4, -8]])
print(A)

[[-1  3 -2  4]
 [ 2 -6  1 -2]
 [ 1 -3  4 -8]]


In [54]:
np.linalg.matrix_rank(A)

2

$x = (A^{T}A)^{-1}A^Tb$

In [56]:
A2 = A.T@A

print(A2)

[[  6 -18   8 -16]
 [-18  54 -24  48]
 [  8 -24  21 -42]
 [-16  48 -42  84]]


In [57]:
np.linalg.matrix_rank(A2)

2

In [ ]:
A.dot(np.linalg.pinv(A).dot(b))

$A*(A^{T}A)^{-1}b$

In [58]:
A.dot(np.linalg.pinv(A).dot(b)).round() == b

array([[False],
       [False],
       [False]])

**Sol: No se puede calcular la solución, porque el rango tiene que ser igual al número de columnas** 

#### c) 
$x_1 + x_2 + 2x_3 +x_4= 1$ \
$x_2 + -x_2 - x_3 +x_4= 0$ \
$x_2 + x_3= -1$ \
$x_1 + x_2 +x4= 2$

In [65]:
A = np.array([[1,1,2,1],[0,0,-1,1],[0,1,1,0],[1,1,0,1]])
b = np.array([[1],[0],[-1],[2]])
print(A)

[[ 1  1  2  1]
 [ 0  0 -1  1]
 [ 0  1  1  0]
 [ 1  1  0  1]]


In [62]:
np.linalg.det(A)

-2.0

In [67]:
x = np.linalg.inv(A)@b
print(x)

[[ 3. ]
 [-0.5]
 [-0.5]
 [-0.5]]


In [63]:
A = np.array([[1,1,2,1],[1,-1,-1,1],[0,1,1,0],[1,1,0,1]])
print(A)

[[ 1  1  2  1]
 [ 1 -1 -1  1]
 [ 0  1  1  0]
 [ 1  1  0  1]]


In [64]:
np.linalg.det(A) 

0.0

#### d) Given the matrix A: 


$A = \frac{1}{10} \begin{pmatrix}1 & 1 & 1 & 1 \\ 1 & 1 & -1 & -1 \\ 1 & -1 & 1 & -1 \\ 1 & -1 & -1 & 1\end{pmatrix} \begin{pmatrix}2 & 0 \\ 1 & 0\\ 0 & 0 \\ 0 & 0 \end{pmatrix} \begin{pmatrix}3 & -4 \\ 4 & 3 \end{pmatrix} $

Find the solution of the following system $A\vec{x} = \vec{b}$

$\vec{b} = \begin{pmatrix}1 \\ 2 \\ 3 \\ 4 \end{pmatrix}$

In [69]:
A1 = np.array([[1,1,1,1],[1,1,-1,-1],[1,-1,1,-1],[1,-1,-1,1]])
A2 = np.array([[2,0],[1,0],[0,0],[0,0]])
A3 = np.array([[3,-4],[4,3]])

b = np.array([[1],[2],[3],[4]])

In [71]:
print(A1.shape)
print(A2.shape)
print(A3.shape)

(4, 4)
(4, 2)
(2, 2)


In [83]:
A = (1/10)*A1@A2@A3
print(A)

[[ 1.  -0.5]
 [ 1.  -0.5]
 [ 0.2 -1.1]
 [ 0.2 -1.1]]


In [72]:
np.linalg.matrix_rank(A)

1

$A = \frac{1}{10} \begin{pmatrix}1 & 1 & 1 & 1 \\ 1 & 1 & -1 & -1 \\ 1 & -1 & 1 & -1 \\ 1 & -1 & -1 & 1\end{pmatrix} \begin{pmatrix}2 & 0 \\ 0 & 1\\ 0 & 0 \\ 0 & 0 \end{pmatrix} \begin{pmatrix}3 & -4 \\ 4 & 3 \end{pmatrix} $

In [78]:
A1 = np.array([[1,1,1,1],[1,1,-1,-1],[1,-1,1,-1],[1,-1,-1,1]])
A2 = np.array([[2,0],[0,1],[0,0],[0,0]])
A3 = np.array([[3,-4],[4,3]])

b = np.array([[1],[2],[3],[4]])

In [79]:
A = (1/10)*A1@A2@A3
print(A)

[[ 1.  -0.5]
 [ 1.  -0.5]
 [ 0.2 -1.1]
 [ 0.2 -1.1]]


In [80]:
np.linalg.matrix_rank(A)

2

In [82]:
 x = np.linalg.inv(A.T@A)@A.T@b
print(x)

[[-0.1]
 [-3.2]]
