<a href="https://colab.research.google.com/github/KayKozaronek/03_Courses/blob/master/S%2BP_Week_2_Lesson_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Preparing features and labels notebook


In [0]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

In [4]:
# Create a Dataset with tf and print its 10 values
dataset = tf.data.Dataset.range(10)
for value in dataset:
  print(value.numpy())

0
1
2
3
4
5
6
7
8
9


In [11]:
# Create a window which moves at 1 frame
# Print all the values in the window dataset
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(size=5, shift =1)
for window in dataset:
  for value in window:
    print(value.numpy(), end= " ")
  print()

0 1 2 3 4 
1 2 3 4 5 
2 3 4 5 6 
3 4 5 6 7 
4 5 6 7 8 
5 6 7 8 9 
6 7 8 9 
7 8 9 
8 9 
9 


In [16]:
# Truncate the window to have a uniform lenght of 5
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(size=5, shift =1, drop_remainder =True)
for window in dataset:
  for value in window:
    print(value.numpy(), end= " ")
  print()

0 1 2 3 4 
1 2 3 4 5 
2 3 4 5 6 
3 4 5 6 7 
4 5 6 7 8 
5 6 7 8 9 


In [23]:
# Use a flat_map to assign the window a batch of 5
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(size =5, shift = 1, drop_remainder = True)
dataset = dataset.flat_map(lambda window : window.batch(5))
for window in dataset:
  print(window.numpy())

[0 1 2 3 4]
[1 2 3 4 5]
[2 3 4 5 6]
[3 4 5 6 7]
[4 5 6 7 8]
[5 6 7 8 9]


In [27]:
# Divide the window into data and labels
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(size =5, shift = 1, drop_remainder =True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1:]))
for x,y in dataset:
  print(x.numpy(), y.numpy())

[0 1 2 3] [4]
[1 2 3 4] [5]
[2 3 4 5] [6]
[3 4 5 6] [7]
[4 5 6 7] [8]
[5 6 7 8] [9]


In [28]:
# Shuffle the dataset
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(size =5, shift =1, drop_remainder = True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1:]))
dataset = dataset.shuffle(buffer_size = 10)
for x,y in dataset:
  print(x.numpy(), y.numpy())

[1 2 3 4] [5]
[4 5 6 7] [8]
[2 3 4 5] [6]
[0 1 2 3] [4]
[3 4 5 6] [7]
[5 6 7 8] [9]


In [31]:
# batch the data into 2
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5,1,drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1:]))
dataset = dataset.shuffle(buffer_size = 10)
dataset = dataset.batch(2).prefetch(1)
for x,y in dataset:
  print("x = ", x.numpy())
  print("y = ", y.numpy())

x =  [[3 4 5 6]
 [0 1 2 3]]
y =  [[7]
 [4]]
x =  [[5 6 7 8]
 [2 3 4 5]]
y =  [[9]
 [6]]
x =  [[1 2 3 4]
 [4 5 6 7]]
y =  [[5]
 [8]]
